## Garry's Mod RTX Remixed rtx.conf

### Params
rtx.autoExposure.evMaxValue = 4
rtx.autoExposure.evMinValue = -2
rtx.autoExposure.exposureCenterMeteringEnabled = True
rtx.capture.correctBakedTransforms = True
rtx.bloom.steps = 5
rtx.bloom.burnIntensity = 0.5
rtx.bloom.luminanceThreshold = 0
rtx.viewModel.scale = 0.250
rtx.fallbackLightMode = 0
rtx.localtonemap.useAgX = True
rtx.localtonemap.exposure = 0.6
rtx.localtonemap.finalizeWithACES = False
rtx.tonemap.exposureBias = 0
rtx.tonemap.dynamicRange = 15
rtx.tonemappingMode = 1
rtx.defaultToAdvancedUI = True
rtx.zUp = True
rtx.suppressLightKeeping = True
rtx.viewModel.enable = True
rtx.skyReprojectToMainCameraSpace = True
rtx.skyBrightness = 1
rtx.skyReprojectScale = 17
rtx.useObsoleteHashOnTextureUpload = True
rtx.lightConversionSphereLightFixedRadius = 9
rtx.skyAutoDetect = 2
rtx.detectUITextures = False
rtx.enableMultiStageTextureFactorBlending = True
rtx.lightConversionSphereLightFixedRadius = 9
rtx.skyMinZThreshold = 0.900
rtx.ignoreGameDirectionalLights = True
rtx.ignoreGamePointLights = True
rtx.ignoreGameSpotLights = True
rtx.raytracedRenderTarget.enable = True
rtx.neeCache.enable = True
rtx.neeCache.enableAnalyticalLight = False
rtx.risLightSampleCount = 32
rtx.di.initialSampleCount = 32
rtx.di.spatialSamples = 4
rtx.di.enableBestLightSampling = True
rtx.di.maxHistoryLength = 1
rtx.di.enableRayTracedBiasCorrection = True
rtx.di.enableSpatialReuse = True
rtx.di.enableDenoiserConfidence = True
rtx.di.enableDenoiserGradient = True
rtx.denoiseDirectAndIndirectLightingSeparately = True
